structure:
  - .github/workflows/test.yaml:
      content: |
        name: test-perl

        on:
          push:
            branches: [ master ]
          pull_request:
            branches: [ master ]

        jobs:
          test:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@{{@ "actions/checkout" | latest_release @}}

              - name: Set up Perl
                uses: shogo82148/actions-setup-perl@{{@ "shogo82148/actions-setup-perl" | latest_release @}}
                with:
                  perl-version: '5.36'

              - name: Setup Python
                uses: actions/setup-python@{{@ "actions/setup-python" | latest_release @}}
                with:
                  python-version: '3.x'

              - name: Install dependencies
                run: |
                  sudo apt-get update
                  sudo apt-get install -y librrds-perl \
                  libjson-perl \
                  libhtml-parser-perl \
                  libcgi-pm-perl \
                  libipc-run-perl

              - name: Run tests
                run: |
                  export PERL5LIB=$PERL5LIB:/usr/share/perl5
                  prove -lrv t > tap.out
                  cat tap.out

              - name: Convert TAP to Markdown inline
                run: |
                  python3 ./scripts/tap2md.py tap.out > results.md

              - name: Show Markdown Test Results as step summary
                run: cat results.md >> $GITHUB_STEP_SUMMARY

              - name: Upload Markdown Test Results
                uses: actions/upload-artifact@{{@ "actions/upload-artifact" | latest_release @}}
                with:
                  name: test-results-markdown
                  path: results.md

              - name: Upload TAP Test Results
                uses: actions/upload-artifact@{{@ "actions/upload-artifact" | latest_release @}}
                with:
                  name: test-results-tap
                  path: tap.out

folders:
  - ./:
      struct:
        - github/workflows/pre-commit
        - github/workflows/release-drafter
        - github/workflows/run-struct
        - github/workflows/stale
      with:
        github_token: ${{ secrets.STRUCT_RUN_TOKEN }}
